"""initial

Revision ID: 1ad6ae75b721
Revises: 3322038c81ec
Create Date: 2020-07-23 17:22:55.481576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad6ae75b721'
down_revision = '3322038c81ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
