"""added warehouse settings

Revision ID: 271c66197073
Revises: f877768e6808
Create Date: 2020-08-12 00:13:08.562873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271c66197073'
down_revision = 'f877768e6808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_tags_warehouse_id_warehouses'), 'warehouses', ['warehouse_id'], ['id'])

    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settings', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_column('settings')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tags_warehouse_id_warehouses'), type_='foreignkey')
        batch_op.drop_column('warehouse_id')

    # ### end Alembic commands ###
