"""article tags patch

Revision ID: 8d3a7955b85f
Revises: f877768e6808
Create Date: 2020-07-27 19:50:34.519846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d3a7955b85f'
down_revision = 'f877768e6808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_tags_warehouse_id_warehouses'), 'tags', 'warehouses', ['warehouse_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tags_warehouse_id_warehouses'), 'tags', type_='foreignkey')
    op.drop_column('tags', 'warehouse_id')
    # ### end Alembic commands ###
