"""initial

Revision ID: 944198881db6
Revises: 
Create Date: 2020-04-27 18:18:31.943433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '944198881db6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('api_key', name=op.f('uq_users_api_key')),
    sa.UniqueConstraint('mail', name=op.f('uq_users_mail'))
    )
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouses'))
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_locations_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations'))
    )
    op.create_table('references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_references_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_references'))
    )
    op.create_table('warehouse_aces',
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_warehouse_aces_user_id_users')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_warehouse_aces_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('warehouse_id', 'user_id', name=op.f('pk_warehouse_aces'))
    )
    op.create_table('items',
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_items_location_id_locations')),
    sa.ForeignKeyConstraint(['reference_id'], ['references.id'], name=op.f('fk_items_reference_id_references')),
    sa.PrimaryKeyConstraint('reference_id', 'location_id', name=op.f('pk_items'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    op.drop_table('warehouse_aces')
    op.drop_table('references')
    op.drop_table('locations')
    op.drop_table('warehouses')
    op.drop_table('users')
    # ### end Alembic commands ###
