"""article tags

Revision ID: f877768e6808
Revises: 3afb15af9820
Create Date: 2020-07-27 17:33:17.422434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f877768e6808'
down_revision = '3afb15af9820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('created', sa.TIMESTAMP(), nullable=True),
    sa.Column('modified', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_table('ArticleTag',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_ArticleTag_article_id_articles')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_ArticleTag_tag_id_tags')),
    sa.PrimaryKeyConstraint('article_id', 'tag_id', name=op.f('pk_ArticleTag'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ArticleTag')
    op.drop_table('tags')
    # ### end Alembic commands ###
